name: jakubvodak
favicon: null
layout_spectrum: 0.039139472879469395
typography_spectrum: 0.28289692336693406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.12632127245888114
  lightness: 0.18273844779469073
  saturation: 0.950863981153816
  rhythmicContrast: 0.9593079434707761
purpose: []
